flysystem:
    storages:
        default.storage:
            adapter: 'aws'
            options:
                client: 'aws.images.s3'
                bucket: '%env(resolve:BUCKET)%'
                prefix: '%env(resolve:PREFIX)%'