security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        user_provider:
            id: App\Security\Core\User\UserProvider

    firewalls:
        register:
            pattern: ^/api/v1/users/register
            methods: [POST]
            security: false
        resend_activation_email:
            pattern: ^/api/v1/users/resend_activation_email
            method: [POST]
            security: false
        docs:
            patter: ^/api/v1/docs
            method: [GET]
            security: false
        login:
            pattern: /api/v1/users/login
            stateless: true
            anonymous: true
            provider: user_provider
            json_login:
                check_path: /api/v1/users/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failer_handler: lexik_jwt_authentication.handler.authentication_failure

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
