security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        users_in_memory: { memory: null }

    firewalls:
        register:
            pattern: ^/api/v1/users/register
            methods: [POST]
            security: false
        resend_activation_email:
            pattern: ^/api/v1/users/resend_activation_email
            method: [POST]
            security: false
        docs:
            patter: ^/api/v1/docs
            method: [GET]
            security: false

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
